### PR TITLE
Use pathlib to modify paths

### PR DESCRIPTION
**Pull request by hugobuddel**

### CODE REVIEW

**Comment by hugobuddel** [comment]
Otherwise the files are called `FLAT.fits_0`, while I suppose they should be `FLAT_0.fits`

**Comment by hugobuddel** [comment]
Oh I missed your changes, so now this PR is broken. Please don't merge it. But you get the drift I suppose. Maybe I'll create a better PR later

**Comment by eiseleb47** [comment]
I fixed the index error for the flat naming in the prep file. I also adjusted the wkf file so now it should run normally again.

**Comment by hugobuddel** [comment]
Great, I'll close this. I just fixed it for myself and then thought, well might as well create a pull request, but didn't notice you made commits in the meantime.

Learning to use `pathlib` will make your life easier, so I recommend it. But for now it doesn't really matter.

**Pull request closed without merging**
